[build]
  command = "npm run build"
  publish = "dist"
  node_version = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  framework = "#custom"